services:
  node-server:
    image: sabz333/osrs-node:latest
    ports:
      - 8080:3000
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - USER_AGENT_HEADER=OSRS GE Tracker Website - @Sabz333 on the wiki & discord
      - DB_USER=$POSTGRES_USER
      - DB_HOST=postgresdb
      - DB_DBNAME=$POSTGRES_DB
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_PORT=5432
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:16.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
volumes:
  db-data: